services:
  api:
    container_name: mammals_api

    build:
      context: .
    networks:
      - mammals_network
    # command:
    #   npx prisma migrate dev
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: mammals_database

    image: postgres:17.2-alpine3.20
    networks:
      - mammals_network

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data

    volumes:
     - mammals_db_data:/var/lib/postgresql/data

networks:
  mammals_network:
volumes:
  mammals_db_data:
